version: '2'
services:
  microrisque-postgresql:
    image: postgres:12.3
    volumes:
        - ~/volumes/jhipster/microrisque/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5436:5432
